/**
 * 芳香疗法植物精油知识库
 *
 * 单方精油50种 + 纯露20种 + 基础油20种
 *
 * 参考资料：
 * - 《芳香疗法大百科》(Patricia Davis)
 * - 《精油图鉴》(温佑君) 商周出版
 * - 《芳香疗法实证学》(Monika Werner)
 * - AEUA欧洲芳香疗法学会教材
 * - 《Complete Aromatherapy Handbook》(Susanne Fischer-Rizzi)
 * - IFPA/NAHA 国际芳疗师认证教材
 */

/** 50种单方精油 */
export const ESSENTIAL_OILS = {
  // === 花香类 ===
  薰衣草: {
    latin: 'Lavandula angustifolia',
    family: '唇形科',
    extraction: '水蒸气蒸馏法',
    part: '花穗',
    aroma: '清新花香，微带草本气息',
    properties: ['镇静安神', '修复再生', '平衡油脂', '缓解焦虑', '助眠'],
    indications: ['失眠', '焦虑', '皮肤修复', '轻度烫伤', '头痛'],
    contraindications: '低血压者慎用大量',
    blends: ['佛手柑', '天竺葵', '迷迭香'],
    reference: '《精油图鉴》温佑君, 商周出版; AEUA教材 Module 3',
  },
  玫瑰: {
    latin: 'Rosa damascena',
    family: '蔷薇科',
    extraction: '水蒸气蒸馏法/溶剂萃取',
    part: '花瓣',
    aroma: '浓郁甜美花香',
    properties: ['抗衰老', '调节内分泌', '美白淡斑', '抗忧郁', '催情'],
    indications: ['皮肤老化', '经期不适', '情绪低落', '干燥肌肤'],
    contraindications: '孕期前三个月避免使用',
    blends: ['檀香', '橙花', '茉莉'],
    reference: '《芳香疗法大百科》Patricia Davis; AEUA教材 Module 5',
  },
  茉莉: {
    latin: 'Jasminum grandiflorum',
    family: '木犀科',
    extraction: '溶剂萃取(原精)',
    part: '花朵',
    aroma: '浓郁醉人花香',
    properties: ['抗忧郁', '催情', '护肤', '平衡荷尔蒙'],
    indications: ['情绪低落', '皮肤干燥', '经期不适', '产后抑郁'],
    contraindications: '孕期避免',
    blends: ['玫瑰', '檀香', '柑橘类'],
    reference: '《芳香疗法实证学》Monika Werner',
  },
  橙花: {
    latin: 'Citrus aurantium var. amara',
    family: '芸香科',
    extraction: '水蒸气蒸馏法',
    part: '花朵',
    aroma: '清雅花香，带柑橘底韵',
    properties: ['抗焦虑', '美白', '促进细胞再生', '镇静'],
    indications: ['焦虑', '失眠', '敏感肌', '妊娠纹'],
    contraindications: '无明显禁忌',
    blends: ['薰衣草', '玫瑰', '佛手柑'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 4',
  },
  依兰依兰: {
    latin: 'Cananga odorata',
    family: '番荔枝科',
    extraction: '水蒸气蒸馏法',
    part: '花朵',
    aroma: '浓郁甜美异国花香',
    properties: ['抗忧郁', '催情', '平衡油脂', '降血压'],
    indications: ['焦虑', '失眠', '油性肌肤', '高血压'],
    contraindications: '过量可能引起头痛',
    blends: ['佛手柑', '檀香', '柠檬'],
    reference: '《芳香疗法大百科》; IFPA教材',
  },
  天竺葵: {
    latin: 'Pelargonium graveolens',
    family: '牻牛儿苗科',
    extraction: '水蒸气蒸馏法',
    part: '叶片',
    aroma: '甜美的玫瑰花香混合薄荷气息',
    properties: ['平衡荷尔蒙', '抗菌', '收敛', '驱虫'],
    indications: ['经期不适', '油性肌肤', '情绪波动', '蚊虫叮咬'],
    contraindications: '孕期避免',
    blends: ['薰衣草', '佛手柑', '玫瑰'],
    reference: '《精油图鉴》温佑君; NAHA教材',
  },
  洋甘菊_罗马: {
    latin: 'Chamaemelum nobile',
    family: '菊科',
    extraction: '水蒸气蒸馏法',
    part: '花朵',
    aroma: '甜美的苹果香气',
    properties: ['镇静安神', '抗过敏', '消炎', '促进消化'],
    indications: ['失眠', '焦虑', '敏感肌', '消化不良'],
    contraindications: '菊科过敏者避免',
    blends: ['薰衣草', '橙花', '玫瑰'],
    reference: '《芳香疗法大百科》; AEUA教材 Module 2',
  },
  洋甘菊_德国: {
    latin: 'Matricaria recutita',
    family: '菊科',
    extraction: '水蒸气蒸馏法',
    part: '花朵',
    aroma: '浓郁草本甜香，深蓝色',
    properties: ['强力抗炎', '抗过敏', '促进愈合', '镇静'],
    indications: ['湿疹', '皮炎', '过敏', '炎症'],
    contraindications: '菊科过敏者避免',
    blends: ['薰衣草', '乳香', '没药'],
    reference: '《芳香疗法实证学》; AEUA教材 Module 2',
  },

  // === 木质类 ===
  檀香: {
    latin: 'Santalum album',
    family: '檀香科',
    extraction: '水蒸气蒸馏法',
    part: '木心',
    aroma: '温暖、木质、甜美的持久香气',
    properties: ['安神冥想', '紧致肌肤', '抗炎', '催情', '利尿'],
    indications: ['失眠', '焦虑', '皮肤松弛', '呼吸道感染'],
    contraindications: '无明显禁忌',
    blends: ['玫瑰', '薰衣草', '佛手柑'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 7',
  },
  雪松: {
    latin: 'Cedrus atlantica',
    family: '松科',
    extraction: '水蒸气蒸馏法',
    part: '木材',
    aroma: '温暖木质香，略带松脂气息',
    properties: ['收敛', '抗菌', '促进淋巴循环', '驱虫'],
    indications: ['油性肌肤', '头皮屑', '呼吸道感染', '焦虑'],
    contraindications: '孕期避免',
    blends: ['檀香', '薰衣草', '佛手柑'],
    reference: '《芳香疗法大百科》; IFPA教材',
  },
  丝柏: {
    latin: 'Cupressus sempervirens',
    family: '柏科',
    extraction: '水蒸气蒸馏法',
    part: '枝叶/球果',
    aroma: '清新木质香，微带烟熏气息',
    properties: ['收敛', '促进循环', '止血', '抗痉挛'],
    indications: ['静脉曲张', '水肿', '多汗', '咳嗽'],
    contraindications: '孕期避免',
    blends: ['天竺葵', '柠檬', '杜松'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 6',
  },
  花梨木: {
    latin: 'Aniba rosaeodora',
    family: '樟科',
    extraction: '水蒸气蒸馏法',
    part: '木心',
    aroma: '温暖木质花香',
    properties: ['促进细胞再生', '抗皱', '抗忧郁', '免疫提升'],
    indications: ['皮肤老化', '皱纹', '免疫力低下'],
    contraindications: '无明显禁忌',
    blends: ['玫瑰', '乳香', '檀香'],
    reference: '《芳香疗法实证学》Monika Werner',
  },
  茶树: {
    latin: 'Melaleuca alternifolia',
    family: '桃金娘科',
    extraction: '水蒸气蒸馏法',
    part: '叶片',
    aroma: '清新药草气息，略带辛辣',
    properties: ['强力抗菌', '抗病毒', '抗真菌', '免疫提升'],
    indications: ['痤疮', '真菌感染', '感冒', '口腔感染'],
    contraindications: '敏感肌需稀释',
    blends: ['薰衣草', '柠檬', '尤加利'],
    reference: '《芳香疗法大百科》; AEUA教材 Module 3',
  },
  尤加利: {
    latin: 'Eucalyptus globulus',
    family: '桃金娘科',
    extraction: '水蒸气蒸馏法',
    part: '叶片',
    aroma: '清新强烈樟脑气息',
    properties: ['强力抗菌', '祛痰', '抗病毒', '提神醒脑'],
    indications: ['感冒', '鼻塞', '咳嗽', '肌肉酸痛'],
    contraindications: '高血压者慎用; 婴幼儿避免',
    blends: ['薄荷', '茶树', '薰衣草'],
    reference: '《芳香疗法大百科》; IFPA教材',
  },
  乳香: {
    latin: 'Boswellia carterii',
    family: '橄榄科',
    extraction: '水蒸气蒸馏法',
    part: '树脂',
    aroma: '温暖树脂香，略带柑橘和松木气息',
    properties: ['抗衰老', '促进细胞再生', '抗炎', '冥想安神'],
    indications: ['皮肤老化', '皱纹', '呼吸道感染', '焦虑'],
    contraindications: '无明显禁忌',
    blends: ['没药', '檀香', '玫瑰'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 7',
  },
  没药: {
    latin: 'Commiphora myrrha',
    family: '橄榄科',
    extraction: '水蒸气蒸馏法',
    part: '树脂',
    aroma: '温暖、烟熏、略带苦味的树脂香',
    properties: ['强力抗炎', '促进愈合', '抗真菌', '收敛'],
    indications: ['口腔溃疡', '皮肤感染', '伤口愈合', '牙龈炎'],
    contraindications: '孕期避免',
    blends: ['乳香', '檀香', '薰衣草'],
    reference: '《芳香疗法大百科》; AEUA教材 Module 7',
  },
  广藿香: {
    latin: 'Pogostemon cablin',
    family: '唇形科',
    extraction: '水蒸气蒸馏法',
    part: '叶片',
    aroma: '浓郁泥土气息，微甜',
    properties: ['抗炎', '抗忧郁', '收敛', '驱虫'],
    indications: ['皮炎', '焦虑', '油性肌肤', '蚊虫'],
    contraindications: '无明显禁忌',
    blends: ['佛手柑', '檀香', '玫瑰'],
    reference: '《精油图鉴》温佑君; NAHA教材',
  },

  // === 柑橘类 ===
  柠檬: {
    latin: 'Citrus limon',
    family: '芸香科',
    extraction: '冷压法',
    part: '果皮',
    aroma: '清新明亮的柑橘香气',
    properties: ['净化', '提神', '抗菌', '促进循环', '美白'],
    indications: ['疲劳', '注意力不集中', '油性肌肤', '空气净化'],
    contraindications: '光敏性，使用后12小时避免日晒',
    blends: ['薰衣草', '薄荷', '尤加利'],
    reference: '《芳香疗法大百科》; AEUA教材 Module 1',
  },
  甜橙: {
    latin: 'Citrus sinensis',
    family: '芸香科',
    extraction: '冷压法',
    part: '果皮',
    aroma: '甜美温暖的柑橘香',
    properties: ['抗忧郁', '助消化', '镇静', '免疫提升'],
    indications: ['焦虑', '失眠', '消化不良', '情绪低落'],
    contraindications: '轻微光敏性',
    blends: ['薰衣草', '乳香', '肉桂'],
    reference: '《芳香疗法大百科》; IFPA教材',
  },
  佛手柑: {
    latin: 'Citrus bergamia',
    family: '芸香科',
    extraction: '冷压法',
    part: '果皮',
    aroma: '清新花香柑橘调，类似伯爵茶',
    properties: ['抗忧郁', '抗菌', '镇静', '促进消化'],
    indications: ['焦虑', '抑郁', '食欲不振', '痤疮'],
    contraindications: '强光敏性，使用后24小时避免日晒',
    blends: ['薰衣草', '天竺葵', '橙花'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 1',
  },
  葡萄柚: {
    latin: 'Citrus paradisi',
    family: '芸香科',
    extraction: '冷压法',
    part: '果皮',
    aroma: '清新微苦柑橘香',
    properties: ['排水肿', '提神', '抗忧郁', '促进代谢'],
    indications: ['水肿', '疲劳', '情绪低落', '食欲控制'],
    contraindications: '光敏性，避免日晒',
    blends: ['丝柏', '杜松', '迷迭香'],
    reference: '《芳香疗法大百科》; NAHA教材',
  },

  // === 草本类 ===
  薄荷: {
    latin: 'Mentha piperita',
    family: '唇形科',
    extraction: '水蒸气蒸馏法',
    part: '全株',
    aroma: '清凉强烈薄荷气息',
    properties: ['提神醒脑', '止痛', '止痒', '退热', '助消化'],
    indications: ['头痛', '恶心', '肌肉酸痛', '疲劳', '消化不良'],
    contraindications: '婴幼儿避免面部使用; 孕期慎用',
    blends: ['薰衣草', '迷迭香', '柠檬'],
    reference: '《芳香疗法大百科》; AEUA教材 Module 3',
  },
  迷迭香: {
    latin: 'Rosmarinus officinalis',
    family: '唇形科',
    extraction: '水蒸气蒸馏法',
    part: '叶片/花',
    aroma: '清新强烈草本香气',
    properties: ['提神醒脑', '增强记忆', '促进循环', '止痛'],
    indications: ['记忆力减退', '肌肉酸痛', '疲劳', '头皮屑'],
    contraindications: '高血压者慎用; 孕期避免',
    blends: ['薄荷', '柠檬', '薰衣草'],
    reference: '《精油图鉴》温佑君; IFPA教材',
  },
  百里香: {
    latin: 'Thymus vulgaris',
    family: '唇形科',
    extraction: '水蒸气蒸馏法',
    part: '全株',
    aroma: '强烈药草气息',
    properties: ['强力抗菌', '抗病毒', '免疫提升', '祛痰'],
    indications: ['感冒', '咳嗽', '呼吸道感染', '免疫力低下'],
    contraindications: '高血压者慎用; 皮肤刺激性强需稀释',
    blends: ['柠檬', '尤加利', '茶树'],
    reference: '《芳香疗法实证学》; AEUA教材 Module 3',
  },
  罗勒: {
    latin: 'Ocimum basilicum',
    family: '唇形科',
    extraction: '水蒸气蒸���法',
    part: '全株',
    aroma: '温暖、甜美的香料气息',
    properties: ['提神', '助消化', '抗痉挛', '抗忧郁'],
    indications: ['消化不良', '疲劳', '头痛', '情绪低落'],
    contraindications: '孕期避免',
    blends: ['柠檬', '薰衣草', '佛手柑'],
    reference: '《芳香疗法大百科》; NAHA教材',
  },

  // === 香料类 ===
  生姜: {
    latin: 'Zingiber officinale',
    family: '姜科',
    extraction: '水蒸气蒸馏法',
    part: '根茎',
    aroma: '温暖辛辣姜香',
    properties: ['温阳散寒', '止痛', '助消化', '抗炎', '催情'],
    indications: ['关节疼痛', '消化不良', '寒性体质', '恶心'],
    contraindications: '敏感肌需大量稀释',
    blends: ['甜橙', '肉桂', '柠檬'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 8',
  },
  肉桂: {
    latin: 'Cinnamomum zeylanicum',
    family: '樟科',
    extraction: '水蒸气蒸馏法',
    part: '树皮',
    aroma: '温暖甜美的香料气息',
    properties: ['强力抗菌', '温阳', '抗病毒', '促进循环'],
    indications: ['寒性体质', '免疫力低下', '疲劳'],
    contraindications: '皮肤刺激性极强，必须大量稀释(<0.5%); 孕期避免',
    blends: ['甜橙', '生姜', '丁香'],
    reference: '《芳香疗法实证学》; AEUA教材 Module 8',
  },
  丁香: {
    latin: 'Eugenia caryophyllata',
    family: '桃金娘科',
    extraction: '水蒸气蒸馏法',
    part: '花苞',
    aroma: '强烈温暖香料气息',
    properties: ['强力止痛', '抗菌', '抗病毒', '麻醉'],
    indications: ['牙痛', '口腔感染', '关节疼痛'],
    contraindications: '皮肤刺激性极强，需大量稀释; 孕期避免',
    blends: ['肉桂', '甜橙', '生姜'],
    reference: '《芳香疗法大百科》; IFPA教材',
  },
  黑胡椒: {
    latin: 'Piper nigrum',
    family: '胡椒科',
    extraction: '水蒸气蒸馏法',
    part: '果实',
    aroma: '温暖辛辣的胡椒香气',
    properties: ['温阳', '止痛', '促进循环', '助消化'],
    indications: ['肌肉酸痛', '寒性体质', '消化不良'],
    contraindications: '敏感肌需稀释',
    blends: ['生姜', '薰衣草', '迷迭香'],
    reference: '《精油图鉴》温佑君; AEUA教材 Module 8',
  },
  茴香: {
    latin: 'Foeniculum vulgare',
    family: '伞形科',
    extraction: '水蒸气蒸馏法',
    part: '种子',
    aroma: '甜美的甘草香气',
    properties: ['助消化', '利尿', '促进泌乳', '平衡荷尔蒙'],
    indications: ['消化不良', '水肿', '经期不适', '哺乳期'],
    contraindications: '孕期避免; 癫痫患者避免',
    blends: ['天竺葵', '柠檬', '薰衣草'],
    reference: '《芳香疗法大百科》; NAHA教材',
  },

  // === 树脂类补充 ===
  安息香: {
    latin: 'Styrax benzoin',
    family: '安息香科',
    extraction: '溶剂萃取',
    part: '树脂',
    aroma: '温暖甜美的香草气息',
    properties: ['抗炎', '促进愈合', '镇静', '祛痰'],
    indications: ['咳嗽', '皮肤皲裂', '焦虑'],
    contraindications: '无明显禁忌',
    blends: ['乳香', '檀香', '薰衣草'],
    reference: '《芳香疗法实证学》Monika Werner',
  },

  // === 更多精油(20种) ===
  杜松: { latin: 'Juniperus communis', family: '柏科', extraction: '水蒸气蒸馏法', part: '浆果', properties: ['排水肿', '净化', '抗风湿', '抗菌'], indications: ['水肿', '关节炎', '痤疮'], reference: '《精油图鉴》温佑君' },
  马郁兰: { latin: 'Origanum majorana', family: '唇形科', extraction: '水蒸气蒸馏法', part: '全株', properties: ['镇静', '止痛', '降血压', '抗痉挛'], indications: ['失眠', '肌肉疼痛', '高血压'], reference: '《芳香疗法大百科》' },
  快乐鼠尾草: { latin: 'Salvia sclarea', family: '唇形科', extraction: '水蒸气蒸馏法', part: '全株', properties: ['平衡荷尔蒙', '抗忧郁', '抗痉挛', '镇静'], indications: ['经期不适', '更年期', '焦虑'], reference: '《精油图鉴》; AEUA教材 Module 4' },
  香茅: { latin: 'Cymbopogon nardus', family: '禾本科', extraction: '水蒸气蒸馏法', part: '叶片', properties: ['驱虫', '抗菌', '提神', '除臭'], indications: ['蚊虫叮咬', '空气净化', '疲劳'], reference: '《芳香疗法大百科》' },
  柠檬草: { latin: 'Cymbopogon citratus', family: '禾本科', extraction: '水蒸气蒸馏法', part: '叶片', properties: ['抗菌', '止痛', '驱虫', '提神'], indications: ['肌肉疼痛', '消化不良', '蚊虫'], reference: '《精油图鉴》温佑君' },
  绿花白千层: { latin: 'Melaleuca viridiflora', family: '桃金娘科', extraction: '水蒸气蒸馏法', part: '叶片', properties: ['抗菌', '抗病毒', '免疫提升', '祛痰'], indications: ['感冒', '呼吸道感染'], reference: '《芳香疗法实证学》' },
  苦橙叶: { latin: 'Citrus aurantium leaf', family: '芸香科', extraction: '水蒸气蒸馏法', part: '叶片', properties: ['镇静', '抗焦虑', '助眠', '收敛'], indications: ['失眠', '焦虑', '油性肌肤'], reference: '《精油图鉴》温佑君' },
  莱姆: { latin: 'Citrus aurantifolia', family: '芸香科', extraction: '冷压法', part: '果皮', properties: ['提神', '抗菌', '收敛', '净化'], indications: ['疲劳', '油性肌肤', '空气净化'], reference: '《芳香疗法大百科》' },
  芫荽: { latin: 'Coriandrum sativum', family: '伞形科', extraction: '水蒸气蒸馏法', part: '种子', properties: ['助消化', '止痛', '抗菌', '抗痉挛'], indications: ['消化不良', '关节疼痛'], reference: '《精油图鉴》温佑君' },
  豆蔻: { latin: 'Elettaria cardamomum', family: '姜科', extraction: '水蒸气蒸馏法', part: '种子', properties: ['助消化', '提神', '抗痉挛', '催情'], indications: ['消化不良', '疲劳', '情绪低落'], reference: '《芳香疗法大百科》' },
  白千层: { latin: 'Melaleuca leucadendron', family: '桃金娘科', extraction: '水蒸气蒸馏法', part: '叶片', properties: ['抗菌', '止痛', '抗炎'], indications: ['呼吸道感染', '肌肉疼痛'], reference: '《芳香疗法实证学》' },
  胡萝卜籽: { latin: 'Daucus carota', family: '伞形科', extraction: '水蒸气蒸馏法', part: '种子', properties: ['促进细胞再生', '抗衰老', '美白', '排毒'], indications: ['皮肤老化', '色斑', '肝毒'], reference: '《精油图鉴》温佑君' },
  岩兰草: { latin: 'Vetiveria zizanioides', family: '禾本科', extraction: '水蒸气蒸馏法', part: '根部', properties: ['镇静安神', '抗焦虑', '促进循环', '免疫提升'], indications: ['失眠', '焦虑', '免疫力低下'], reference: '《精油图鉴》; AEUA教材 Module 7' },
  穗花薰衣草: { latin: 'Lavandula latifolia', family: '唇形科', extraction: '水蒸气蒸馏法', part: '花穗', properties: ['抗菌', '祛痰', '止痛', '促进愈合'], indications: ['呼吸道感染', '烧伤', '肌肉疼痛'], reference: '《芳香疗法实证学》' },
  蓝胶尤加利: { latin: 'Eucalyptus globulus', family: '桃金娘科', extraction: '水蒸气蒸馏法', part: '叶片', properties: ['抗菌', '祛痰', '提神'], indications: ['感冒', '鼻塞', '咳嗽'], reference: '《芳香疗法大百科》' },
  松树: { latin: 'Pinus sylvestris', family: '松科', extraction: '水蒸气蒸馏法', part: '针叶', properties: ['抗菌', '祛痰', '提神', '抗炎'], indications: ['呼吸道感染', '疲劳', '关节炎'], reference: '《精油图鉴》温佑君' },
  白松香: { latin: 'Ferula galbaniflua', family: '伞形科', extraction: '水蒸气蒸馏法', part: '树脂', properties: ['抗炎', '抗痉挛', '促进愈合'], indications: ['炎症', '肌肉痉挛', '伤口'], reference: '《芳香疗法实证学》' },
  榄香脂: { latin: 'Canarium luzonicum', family: '橄榄科', extraction: '水蒸气蒸馏法', part: '树脂', properties: ['抗炎', '促进愈合', '祛痰', '镇静'], indications: ['呼吸道感染', '皮肤炎症'], reference: '《精油图鉴》温佑君' },
  桂花: { latin: 'Osmanthus fragrans', family: '木犀科', extraction: '���剂萃取', part: '花朵', properties: ['抗忧郁', '护肤', '抗衰老', '催情'], indications: ['皮肤老化', '情绪低落'], reference: '《芳香疗法大百科》' },
  白玉兰: { latin: 'Michelia alba', family: '木兰科', extraction: '溶剂萃取', part: '花朵', properties: ['镇静', '护肤', '抗忧郁', '降压'], indications: ['焦虑', '皮肤干燥', '高血压'], reference: '《精油图鉴》温佑君' },
};

/** 20种纯露 */
export const HYDROSOLS = {
  玫瑰纯露: { properties: ['补水保湿', '美白淡斑', '舒缓敏感'], pH: '4.1-4.4', indications: ['干燥肌肤', '敏感肌', '熟龄肌'], reference: '《纯露芳香疗法》Suzanne Catty' },
  薰衣草纯露: { properties: ['平衡油脂', '镇静舒缓', '修复再生'], pH: '5.6-5.9', indications: ['油性肌肤', '痘痘肌', '晒后修复'], reference: '《纯露芳香疗法》' },
  橙花纯露: { properties: ['美白提亮', '收敛毛孔', '抗老化'], pH: '3.8-4.5', indications: ['暗沉', '毛孔粗大', '熟龄肌'], reference: '《纯露芳香疗法》' },
  洋甘菊纯露: { properties: ['抗过敏', '消炎镇静', '修复屏障'], pH: '3.0-3.5', indications: ['敏感肌', '湿疹', '红血丝'], reference: '《纯露芳香疗法》' },
  金缕梅纯露: { properties: ['强力收敛', '控油', '消炎'], pH: '3.5-4.0', indications: ['油性肌肤', '毛孔粗大', '痤疮'], reference: '《纯露芳香疗法》' },
  薄荷纯露: { properties: ['清凉镇静', '止痒', '提神'], pH: '6.1-6.3', indications: ['瘙痒', '晒伤', '疲劳'], reference: '《纯露芳香疗法》' },
  茶树纯露: { properties: ['抗菌消炎', '控油', '净化'], pH: '3.9-4.1', indications: ['痤疮', '真菌感染', '头皮屑'], reference: '《纯露芳香疗法》' },
  天竺葵纯露: { properties: ['平衡油脂', '收敛', '驱虫'], pH: '4.6-4.9', indications: ['油性肌肤', '混合肌'], reference: '《纯露芳香疗法》' },
  迷迭香纯露: { properties: ['提神醒脑', '控油', '促进循环'], pH: '4.5-4.7', indications: ['疲劳', '油性头皮', '记忆力减退'], reference: '《纯露芳香疗法》' },
  杜松纯露: { properties: ['排水肿', '净化排毒', '收敛'], pH: '4.2-4.5', indications: ['水肿', '橘皮组织', '痤疮'], reference: '《纯露芳香疗法》' },
  永久花纯露: { properties: ['活血化瘀', '促进愈合', '抗炎'], pH: '4.5-5.0', indications: ['瘀伤', '疤痕', '玫瑰痤疮'], reference: '《纯露芳香疗法》' },
  香蜂草纯露: { properties: ['抗忧郁', '镇静', '助消化'], pH: '5.6-6.0', indications: ['焦虑', '失眠', '消化不良'], reference: '《纯露芳香疗法》' },
  矢车菊纯露: { properties: ['舒缓眼部', '抗炎', '收敛'], pH: '4.7-5.0', indications: ['眼部疲劳', '结膜炎', '浮肿'], reference: '《纯露芳香疗法》' },
  月桂纯露: { properties: ['抗菌', '助消化', '淋巴排毒'], pH: '4.5-5.0', indications: ['消化不良', '淋巴结��大'], reference: '《纯露芳香疗法》' },
  乳香纯露: { properties: ['抗老化', '促进再生', '紧致'], pH: '4.5-5.0', indications: ['皮肤老化', '皱纹', '松弛'], reference: '《纯露芳香疗法》' },
  岩玫瑰纯露: { properties: ['止血', '促进愈合', '抗病毒'], pH: '3.8-4.2', indications: ['伤口', '出血', '病毒感染'], reference: '《纯露芳香疗法》' },
  丝柏纯露: { properties: ['收敛', '促进循环', '止汗'], pH: '4.0-4.5', indications: ['多汗', '静脉曲张', '水肿'], reference: '《纯露芳香疗法》' },
  檀香纯露: { properties: ['保湿', '镇静', '抗炎'], pH: '5.0-6.0', indications: ['干燥肌肤', '敏感肌'], reference: '《纯露芳香疗法》' },
  桂花纯露: { properties: ['美白', '抗氧化', '滋养'], pH: '4.5-5.0', indications: ['暗沉', '老化', '干燥'], reference: '《纯露芳香疗法》' },
  白玉兰纯露: { properties: ['保湿', '镇静', '抗老化'], pH: '5.0-5.5', indications: ['干燥肌肤', '敏感肌'], reference: '《纯露芳香疗法》' },
};

/** 20种基础油(载体油) */
export const CARRIER_OILS = {
  荷荷巴油: { latin: 'Simmondsia chinensis', 质地: '液体蜡', 吸收速度: '快', 稳定性: '极高', 适用: ['所有肤质', '油性肌', '护发'], properties: ['保湿', '平衡油脂', '抗炎'], reference: '《植物油全书》Ruth von Braunschweig' },
  甜杏仁油: { latin: 'Prunus amygdalus dulcis', 质地: '轻薄', 吸收速度: '中等', 稳定性: '中', 适用: ['所有肤质', '婴儿', '敏感肌'], properties: ['滋润', '舒缓', '软化'], reference: '《植物油全书》' },
  葡萄籽油: { latin: 'Vitis vinifera', 质地: '极轻薄', 吸收速度: '快', 稳定性: '低', 适用: ['油性肌', '痤疮肌'], properties: ['抗氧化', '收敛', '控油'], reference: '《植物油全书》' },
  摩洛哥坚果油: { latin: 'Argania spinosa', 质地: '中等', 吸收速度: '中等', 稳定性: '高', 适用: ['所有肤质', '熟龄肌', '护发'], properties: ['抗衰老', '修复', '滋养'], reference: '《植物油全书》' },
  玫瑰果油: { latin: 'Rosa rubiginosa', 质地: '轻薄', 吸收速度: '快', 稳定性: '低', 适用: ['熟龄肌', '疤痕', '色斑'], properties: ['抗衰老', '淡斑', '修复疤痕'], reference: '《植物油全书》' },
  椰子油_分馏: { latin: 'Cocos nucifera', 质地: '极轻薄', 吸收速度: '快', 稳定性: '极高', 适用: ['所有肤质', '护发'], properties: ['保湿', '抗菌', '滋养'], reference: '《植物油全书》' },
  橄榄油: { latin: 'Olea europaea', 质地: '厚重', 吸收速度: '慢', 稳定性: '中', 适用: ['干性肌', '熟龄肌'], properties: ['滋润', '抗炎', '抗氧化'], reference: '《植物油全书》' },
  月见草油: { latin: 'Oenothera biennis', 质地: '轻薄', 吸收速度: '中等', 稳定性: '低', 适用: ['熟龄肌', '更年期', '湿疹'], properties: ['平衡荷尔蒙', '抗炎', '修复屏障'], reference: '《植物油全书》' },
  琉璃苣油: { latin: 'Borago officinalis', 质地: '轻薄', 吸收速度: '中等', 稳定性: '低', 适用: ['熟龄肌', '敏感肌', '湿疹'], properties: ['抗炎', '修复屏障', '抗老化'], reference: '《植物油全书》' },
  小麦胚芽油: { latin: 'Triticum vulgare', 质地: '厚重', 吸收速度: '慢', 稳定性: '极高', 适用: ['熟龄肌', '疤痕'], properties: ['抗氧化', '修复', '滋养'], reference: '《植物油全书》' },
  芝麻油: { latin: 'Sesamum indicum', 质地: '中等', 吸收速度: '慢', 稳定性: '高', 适用: ['干性肌', '阿育吠陀按摩'], properties: ['排毒', '滋润', '温阳'], reference: '《植物油全书》' },
  圣约翰草浸泡油: { latin: 'Hypericum perforatum', 质地: '中等', 吸收速度: '中等', 稳定性: '中', 适用: ['肌肉酸痛', '神经痛', '瘀伤'], properties: ['止痛', '抗炎', '促进愈合'], reference: '《植物油全书》' },
  金盏花浸泡油: { latin: 'Calendula officinalis', 质地: '中等', 吸收速度: '中等', 稳定性: '中', 适用: ['敏感肌', '婴儿', '湿疹'], properties: ['抗炎', '修复', '舒缓'], reference: '《植物油全书》' },
  榛果油: { latin: 'Corylus avellana', 质地: '轻薄', 吸收速度: '快', 稳定性: '高', 适用: ['油性肌', '混合肌'], properties: ['收敛', '控油', '保湿'], reference: '《植物油全书》' },
  澳洲坚果油: { latin: 'Macadamia integrifolia', 质地: '中等', 吸收速度: '中等', 稳定性: '极高', 适用: ['所有肤质', '熟龄肌'], properties: ['保湿', '抗老化', '修复'], reference: '《植物油全书》' },
  杏桃仁油: { latin: 'Prunus armeniaca', 质地: '轻薄', 吸收速度: '中等', 稳定性: '中', 适用: ['所有肤质', '敏感肌'], properties: ['滋润', '舒缓', '软化'], reference: '《植物油全书》' },
  沙棘果油: { latin: 'Hippophae rhamnoides', 质地: '中等', 吸收速度: '中等', 稳定性: '高', 适用: ['熟龄肌', '修复', '晒后'], properties: ['强力抗氧化', '修复', '抗炎'], reference: '《植物油全书》' },
  辣木籽油: { latin: 'Moringa oleifera', 质地: '轻薄', 吸收速度: '快', 稳定性: '极高', 适用: ['所有肤质', '熟龄肌'], properties: ['抗老化', '净化', '保湿'], reference: '《植物油全书》' },
  山茶花油: { latin: 'Camellia oleifera', 质地: '轻薄', 吸收速度: '快', 稳定性: '高', 适用: ['所有肤质', '护发', '婴儿'], properties: ['保湿', '抗老化', '滋养'], reference: '《植物油全书》; 中国传统本草' },
  黑种草油: { latin: 'Nigella sativa', 质地: '中等', 吸收速度: '中等', 稳定性: '中', 适用: ['敏感肌', '湿疹', '痤疮'], properties: ['强力抗炎', '抗过敏', '免疫调节'], reference: '《植物油全书》' },
};

export default { ESSENTIAL_OILS, HYDROSOLS, CARRIER_OILS };
